EXP_NAME: CRNN
SEED: 42
API_KEY: 'a74f58efdf63706877955dc5830d376b0630b0d4'



DATASET:
    datadir: 'text-reg-data/'
    target: 'mjsynth'
    synth_folder: 'mnt/ramdisk/max/90kDICT32px'
    icdar15_folder: 'icdar/icdar15/trainning'
    exp_folder: 'exp'

    resize: 
        height : 32 # height
        width : 100 # width

# DATALOADER:
#     batch_size: 4
#     num_workers: 0


MODEL:
    map_to_seq_hidden: 64
    rnn_hidden: 256
    leaky_relu: False

TRAIN:
    num_training_steps: 1000000
    #neg_rto: 1
    #n_min_neg: 1000
    #epochs: 10000,
    train_batch_size: 16
    #'eval_batch_size': 512,
    #'lr': 0.0005,
    #'show_interval': 10,
    #'valid_interval': 400,
    #'save_interval': 400, #2000, # chu ki save checkpoint
    num_workers : 0
    reload_checkpoint: None
    valid_max_iter: 100
    decode_method: 'greedy'
    beam_size: 10
    #checkpoints_dir: 'checkpoints/'
    use_wandb: True


EVALUATE:
    eval_batch_size: 512
    #'cpu_workers': 4,
    num_workers : 0
    reload_checkpoint: 'checkpoints/crnn_synth90k.pt'
    decode_method: 'beam_search'
    beam_size: 10


TEST:
    IMAGE : 'D:/data/TextReg/Challengeee' # img data path để test
    ANNOTATION_TEST : 'text-reg-data/base-data/mnt/ramdisk/max/90kDICT32px/annotation_test.txt'
    test_batch_size: 16
    #reload_checkpoint: 'checkpoints/crnn_synth90k.pt',
    decode_method: 'beam_search'
    beam_size: 10
    
    

OPTIMIZER:
    optim_name: 'adam' #'RMS''sgd'
    lr: 0.001 #0.0001
    weight_decay: 0.0005
    momentum: 0.9


SCHEDULER:
    min_lr:  0.0001 #0.00001
    warmup_ratio: 0.1
    use_scheduler: True


LOG:
    log_interval: 1
    eval_interval: 50


RESULT:
    savedir: 'saved_model'
    vis_test_dir: 'vis_test_dir'

RESUME:
    bestmodel: 'best_model.pth'